sudo: required
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  latexmk texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
  texlive-generic-recommended texlive-science
script:
- latexmk -interaction=nonstopmode -pdf -halt-on-error adk_whitepaper.tex
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kSgfm39sW+sV1Tvm7psx7JyhXNAW+DPGj7Qmcy9VlhYIY/m0wK62HrFT7/j785WnhSOy7yhxvDy+bcewP8WpUp4LMht+/bUYK5HfM2EU7c7K8sfQmA7ME+ls/YOpUS7zKntEvQ2QcLdBP79i5O5aqXFkf8kATG/vMtMau66lpSecSuFa6e4mhBagGOk+8L5xLuz2GHZcakAA01MAvNW8V7Bxk8PFBuT3NNERTkS2QqY/JQl+LKg7nTEgvaf4vdtXf1DD8tUj43lDqYDgKE8PgCNnR3fYQ2hqtm+MNhKwmBmI8tIt8wBCmjn6CfA8txnlYiGB5nEwFSS44lqFPyyAN+074Ff1751wK6TkQa3n6uV77Fehec0YbMQ9EjIj6dnv2bbyaLBOLB8DwDDqElD4FW05uBGSHcbXQN0wlfk1NvTInFqmTjji0xNCkmMc3MRPYTccngLXzSqPviPBjl62AHaPStzfKTw8ItCqZPUOpXNKvkhfooMuRRNYOo8rWxGcdTLR5DXxFnvFhU9QTvmiTiv3G4qJRIYhhLgTEqHEjSnZqonZNfOHVEcfRFLKF9OnFr0H9VDBol0m4R10jO5LfG/YDzX+sTivzmXuApjEGx9enVpkqmXj+zbIXaPYIND0reWscMVYcjQ7ANeAg/ojlwhmf5Kd+YusNbB2Vbg4Vfk=
  file: adk_whitepaper.pdf
  on:
    tags: true
    all_branches: true
condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
