sudo: required
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-generic-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build adk_whitepaper.tex
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JZffWz3ZTyk/eqpXqxZShFICai1Pv82nclYAyrZn4VKkQSsnGTLgIwpxWYjH1RNocduq8K8UNTH4PlDBRUZpfCjNH0FxOPWjBPhOquh3XMnhxzx0+7ERexW8I9ewdyE4TUd1zQQxvtDJpckH4omQmDXH4r9j7yst1KJpqSZBweFq0RMmVGuLGXClhRqcVln9qhRg9M4D8gOfU0A6wAlzRnNdIB1CLRrgpG6u6dNGEGxBLvok5x/K/wF05Kf/AjIqpBb8O/eWc3Mv9gJGGcSRdEDOEIzOAoDL9lmJwzwU37FxuWpV63SyYSdRVjfq8bRiJtbdPR8rMS6hNJTYLwWDjPnz7n1AAg7LDeZ5q6H9TUik0Uqwd8UArJPSurq3oiXN5In6UAgEZiWeU/wqEIURVS1QK5uv2kIFxDwVuvOwNNmnJpj8m2rRIFzQYGY34TyZS7Umy4eJymrAU52GTFkvU9Mng/8FQpTIxzrVysH/UlOl8ePUeZz4pdBDRCinM2hV6rPd2EO0pT/IX7ZCVPsHmA3ewilMZyyJ6rLTrrle9APlPMyR3KXVeJjLwHsswceUjwTtKwatD53Q35gq2BYnPnQlYKF2A/xwGupV/Z9qs/Pcf3k/W/kUcLMlBDCs5OSXqPH1M3POeWoE16WaDPcVl3gSCJu/kV4O6sI2+J1vLPE=
  file: _build/adk_whitepaper.pdf
  on:
    tags: true
    all_branches: true
condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
